### ISSUE TITLE
Why does the gtfs-transformer-cli encode feeds with the US-ASCII charset?

### ISSUE THREAD

**Issue by emmambd** [OneBusAway/onebusaway-gtfs-modules#236]
Hi OneBusAway community! I'm Emma Blue, a staff member at [MobilityData](https://mobilitydata.org/), the non-profit that manages and facilitates changes to GTFS. 

**Summary:** 

The gtfs-transformer-cli module encodes feeds in the US-ASCII charset, even though [the spec recommends using UTF-8](https://gtfs.org/schedule/reference/#file-requirements). 

**Steps to reproduce:** 

[Code snippet shared here](https://github.com/MobilityData/gtfs-validator/issues/1713#issue-2183370898)

**Expected behavior:** 

The newly transformed feed is encoded in UTF-8.

**Observed behavior:** 

It's encoded in US-ASCII.

**Comment by kurtraschke** [comment]
As I mentioned in MobilityData/gtfs-validator#1713, I believe this is a misunderstanding/misdiagnosis of the root cause of the original issue, but just to provide some certainty here, I will point out that there is [a test](https://github.com/OneBusAway/onebusaway-gtfs-modules/blob/c955a39947de416b1dfdfd32cd23f4c739302fa3/onebusaway-gtfs/src/test/java/org/onebusaway/gtfs/serialization/GtfsWriterTest.java#L50) in `onebusaway-gtfs` which specifically tests the ability to round-trip GTFS entities which contain non-ASCII text.  Given as this test has been in the codebase for at least the past 14 years (and passing!), and some quick manual tests also confirm that this works as expected, I genuinely doubt that there is an issue here.

A [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) would be helpful in pursuing this further.

**Comment by emmambd** [comment]
Thank you for this in-depth investigation and speedy response @kurtraschke! As mentioned in https://github.com/MobilityData/gtfs-validator/issues/1713#issuecomment-2098710975, I'm closing this issue since it's clear the problem is a need for additional error messaging on the validator, rather than the GTFS Transformer.
